<?xml version="1.0" encoding="utf-8"?><Database Name="dbSoft1" Class="dbCAJA" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=184.168.194.75;Initial Catalog=dbSoft1;Persist Security Info=True;User ID=Soft1" SettingsObjectName="Principal.Properties.Settings" SettingsPropertyName="dbSoft1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Soft1.Caja" Member="Caja">
    <Type Name="Caja">
      <Column Name="NoMvto" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoCuenta" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SaldoInicial" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Deposito" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Retiro" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="SaldoFinal" Type="System.Decimal" DbType="Decimal(20,2)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaMvto" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NoUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cuentas_Caja" Member="Cuentas" ThisKey="NoCuenta" OtherKey="NoCuenta" Type="Cuentas" IsForeignKey="true" />
      <Association Name="Usuarios_Caja" Member="Usuarios" ThisKey="NoUsuario" OtherKey="NoUsuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Soft1.CatCuentas" Member="CatCuentas">
    <Type Name="CatCuentas">
      <Column Name="IdCta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoCuenta" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="MontoMinimo" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TasaInteres" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="PlazoForsozo" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NoUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CatCuentas_Cuentas" Member="Cuentas" ThisKey="IdCta" OtherKey="Idcta" Type="Cuentas" />
    </Type>
  </Table>
  <Table Name="Soft1.Cuentas" Member="Cuentas">
    <Type Name="Cuentas">
      <Column Name="NoCuenta" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Idsocio" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Idcta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MontoApertura" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Depositos" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Retiros" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Decimal(22,2)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaApertura" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NoUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cuentas_Caja" Member="Caja" ThisKey="NoCuenta" OtherKey="NoCuenta" Type="Caja" />
      <Association Name="CatCuentas_Cuentas" Member="CatCuentas" ThisKey="Idcta" OtherKey="IdCta" Type="CatCuentas" IsForeignKey="true" />
      <Association Name="SOCIOS_Cuentas" Member="SOCIOS" ThisKey="Idsocio" OtherKey="IdSocio" Type="SOCIOS" IsForeignKey="true" />
      <Association Name="Usuarios_Cuentas" Member="Usuarios" ThisKey="NoUsuario" OtherKey="NoUsuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Soft1.SOCIOS" Member="SOCIOS">
    <Type Name="SOCIOS">
      <Column Name="IdSocio" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Socio" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="Domicilio" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BuroCredito" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NoUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RFC" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Association Name="SOCIOS_Cuentas" Member="Cuentas" ThisKey="IdSocio" OtherKey="Idsocio" Type="Cuentas" />
    </Type>
  </Table>
  <Table Name="Soft1.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="NoUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Usuarios_Caja" Member="Caja" ThisKey="NoUsuario" OtherKey="NoUsuario" Type="Caja" />
      <Association Name="Usuarios_Cuentas" Member="Cuentas" ThisKey="NoUsuario" OtherKey="NoUsuario" Type="Cuentas" />
    </Type>
  </Table>
  <Table Name="Soft1.SociosV" Member="SociosV">
    <Type Name="SociosV">
      <Column Name="Socio" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="Domicilio" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BuroCredito" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RFC" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="IdSocio" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NoUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spCuentas_Apertura" Method="spCuentas_Apertura">
    <Parameter Name="Idsocio" Parameter="idsocio" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="IdCta" Parameter="idCta" Type="System.Int32" DbType="Int" />
    <Parameter Name="MontoApertura" Parameter="montoApertura" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="NoUsuario" Parameter="noUsuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="spCuentas_AperturaResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="VarChar(143)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>